sudo: required 
services:
  - docker

before_install:
  - docker build -t oliverarias12/docker-react -f Dockerfile.dev .  

 script:
  - docker run oliverarias12/docker-react npm run test -- --coverage